### ISSUE TITLE
ქვესადგურები

### ISSUE THREAD

**Issue by dimakura** [kakheti/pathfinder#10]
გასასწორებელია ძებნა

არის: | უნდა იყოს:
--------|----------------
ზუსტი სიტყვით | Like-ით

ქვესადგურებს უნდა მიებას 6-10კვ ობიექტები და მათი სტატისტიკა ქვესადგურის ნომრის მიხედვით:

| დასამატებელია |
|----------------------|
| 6-10კვ ფიდერები |
| 6-10კვ სატრ. ჯიხურები |
| 6-10კვ საყრდენები  |

ქვესადგურებს უნდა მიებას აბონენტების სტატისტიკა

| დასამატებელია |
|----------------------|
| საყოფაცხოვრებო |
| არა საყოფაცხ. |
| საშ. მოხმარება |

**Comment by shvelo** [comment]
ზუსტი სიტყვით არ არის
