### ISSUE TITLE
თავსართი

### ISSUE THREAD

**Issue by dimakura** [kakheti/pathfinder#7]
ტექსტია შესაცვლელი

N | არის | უნდა იყოს 
---|-------|---------------
1  |  Pathfinder  |  საწყისი
2  |  110-220 კვ | 35-110-220 კვ
3  | სატრ. ჯიხურები | 6-10კვ სატრ. ჯიხურები
4  | 6-10კვ ბოძები | 6-10კვ საყრდენები

**Comment by shvelo** [comment]
Solved
